###
# @name login
POST {{baseUrl}}/signin HTTP/1.1
Content-type: application/json

{
  "username": "exampleuser",
  "password": "somestrongpassword"
}
###
@authToken = {{login.response.body.access_token}}
###

###
GET {{baseUrl}}/users HTTP/1.1
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/users/me HTTP/1.1
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/users/exampleuser HTTP/1.1
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/users/me/wishes HTTP/1.1
Authorization: Bearer {{authToken}}


###
PATCH {{baseUrl}}/users/me HTTP/1.1
Content-type: application/json
Authorization: Bearer {{authToken}}

{
  "username": "exampleuser",
  "about": "exampleuser_patched",
  "avatar": "https://i.pravatar.cc/150?img=3",
  "email": "user@yandex.ru",
  "password": "somestrongpassword"
}

###
POST {{baseUrl}}/signup HTTP/1.1
Content-type: application/json

{
  "username": "exampleuser",
  "about": "exampleuser",
  "avatar": "https://i.pravatar.cc/150?img=3",
  "email": "user@yandex.ru",
  "password": "somestrongpassword"
}

###

POST {{baseUrl}}/signin HTTP/1.1
Content-type: application/json

{
  "username": "exampleuser",
  "password": "somestrongpassword"
}

###